version: '3.8'

services:
  frontend:
    image: frontend
    container_name: seiii-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped
    networks:
      - seiii-network

networks:
  seiii-network:
    driver: bridge
