###
# @name Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "wsq.wsq@outlook.com",
    "password": "12345678"
}

######## RAG

###
# @name newSession
POST {{baseUrl}}/rag/session
Authorization: Bearer {{Login.response.body.data}}

### delete session

DELETE {{baseUrl}}/rag/session/{{newSession.response.body.$..id}}
Authorization: Bearer {{Login.response.body.data}}

### update session title
PUT {{baseUrl}}/rag/session/{{newSession.response.body.$..id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{Login.response.body.data}}

{
    "title": "Hello World"
}

### get sessions
GET {{baseUrl}}/rag/session
    ?page=0
    &page_size=10
Content-Type: application/json
Authorization: Bearer {{Login.response.body.data}}

####### RAG

### postChatMessage
POST {{baseUrl}}/rag/session/{{newSession.response.body.$..id}}/message
Content-Type: application/json
Authorization: Bearer {{Login.response.body.data}}

{
    "content": "新生准入工作组成员包含那些人？"
}

### getChatMessages
GET {{baseUrl}}/rag/session/{{newSession.response.body.$..id}}/message
    ?page=0
    &page_size=10
Authorization: Bearer {{Login.response.body.data}}
